# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20171026_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsetestdata',
            name='handicap',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='horsetestdata',
            name='result',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='horsetestdata',
            name='time',
            field=models.CharField(default=-1, max_length=200),
        ),
    ]
