# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20171027_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsetestdata',
            name='horse_father_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='horsetestdata',
            name='horse_mother_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='horsetestdata',
            name='html_row',
            field=models.TextField(default='-1'),
        ),
        migrations.AlterField(
            model_name='fixturetestdata',
            name='horse_father_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='fixturetestdata',
            name='horse_mother_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='fixturetestdata',
            name='html_row',
            field=models.TextField(default='-1'),
        ),
        migrations.AlterField(
            model_name='resulttestdata',
            name='horse_father_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='resulttestdata',
            name='horse_mother_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='resulttestdata',
            name='html_row',
            field=models.TextField(default='-1'),
        ),
    ]
