# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20171027_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsetestdata',
            name='fixture',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='past_results', to='tests.FixtureTestData'),
            preserve_default=False,
        ),
    ]
