# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20171029_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsetestdata',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_results', to='tests.FixtureTestData'),
        ),
    ]
