# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20171029_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturetestdata',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='horsetestdata',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='resulttestdata',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
