# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20171029_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.DecimalField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture', to='tests.FixtureTestData')),
            ],
        ),
    ]
