# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_horsetestdata_race_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horsetestdata',
            name='race_day',
        ),
    ]
