# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20171026_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horsetestdata',
            name='fixture_test_data',
        ),
        migrations.RemoveField(
            model_name='horsetestdata',
            name='result_test_data',
        ),
    ]
