# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.TextField()),
                ('horse_id', models.IntegerField()),
                ('result', models.IntegerField()),
                ('horse_age', models.TextField()),
                ('horse_father_id', models.IntegerField()),
                ('horse_mother_id', models.IntegerField()),
                ('horse_weight', models.FloatField()),
                ('jockey_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
                ('time', models.TextField()),
                ('handicap', models.IntegerField()),
                ('track_type', models.TextField()),
                ('distance', models.IntegerField()),
                ('city', models.TextField()),
            ],
        ),
    ]
