# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(default=0)),
                ('race_date', models.DateField(blank=True, null=True)),
                ('horse_name', models.CharField(max_length=200)),
                ('horse_id', models.IntegerField()),
                ('horse_age', models.CharField(max_length=200)),
                ('horse_father_id', models.IntegerField()),
                ('horse_mother_id', models.IntegerField()),
                ('horse_weight', models.CharField(max_length=200)),
                ('jockey_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
                ('track_type', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaceDayTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_source', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('city_id', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(default=0)),
                ('race_date', models.DateField(blank=True, null=True)),
                ('horse_name', models.CharField(max_length=200)),
                ('horse_id', models.IntegerField()),
                ('horse_age', models.CharField(max_length=200)),
                ('horse_father_id', models.IntegerField()),
                ('horse_mother_id', models.IntegerField()),
                ('horse_weight', models.CharField(max_length=200)),
                ('jockey_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
                ('track_type', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('result', models.IntegerField(default=-1)),
                ('handicap', models.IntegerField(default=-1)),
                ('time', models.CharField(default=-1, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
