# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='handicap',
        ),
        migrations.RemoveField(
            model_name='result',
            name='result',
        ),
        migrations.RemoveField(
            model_name='result',
            name='time',
        ),
    ]
