# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrapper', '0002_delete_raceresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.TextField()),
                ('horse_id', models.IntegerField()),
                ('result', models.IntegerField()),
                ('horse_age', models.TextField()),
                ('horse_father_id', models.IntegerField()),
                ('horse_mother_id', models.IntegerField()),
                ('horse_weight', models.FloatField()),
                ('jockey_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
                ('time', models.TextField()),
                ('handicap', models.IntegerField()),
                ('track_type', models.TextField()),
                ('distance', models.IntegerField()),
                ('city', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultRowScrapperTestData',
            fields=[
                ('raceresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapper.RaceResult')),
                ('html_row', models.TextField()),
            ],
            bases=('scrapper.raceresult',),
        ),
    ]
