# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20171004_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='handicap',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='result',
            name='result',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='result',
            name='time',
            field=models.CharField(default=-1, max_length=200),
        ),
    ]
