# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_auto_20170901_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='horse_age',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='horse_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='horse_weight',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='track_type',
            field=models.CharField(max_length=200),
        ),
    ]
