# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_resulttestdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttestdata',
            name='html_row',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
