# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_auto_20170903_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultrowscrappertestdata',
            name='raceresult_ptr',
        ),
        migrations.DeleteModel(
            name='ResultRowScrapperTestData',
        ),
    ]
