# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_raceresulttestdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLSourceTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_source', models.TextField()),
                ('url', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=200)),
                ('race_id', models.IntegerField(default=0)),
                ('race_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
