# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_racedaytestdata_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(default=0)),
                ('race_date', models.DateField(blank=True, null=True)),
                ('horse_id', models.IntegerField()),
                ('jockey_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
                ('result', models.IntegerField(default=-1)),
                ('handicap', models.IntegerField(default=-1)),
                ('time', models.CharField(default=-1, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorseTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(default=0)),
                ('race_date', models.DateField(blank=True, null=True)),
                ('jockey_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
                ('horse_name', models.CharField(max_length=200)),
                ('horse_id', models.IntegerField()),
                ('horse_age', models.CharField(max_length=200)),
                ('horse_father_id', models.IntegerField()),
                ('horse_mother_id', models.IntegerField()),
                ('horse_weight', models.CharField(max_length=200)),
                ('track_type', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('html_row', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
