# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_htmlsourcetestdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htmlsourcetestdata',
            old_name='race_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='htmlsourcetestdata',
            name='race_id',
        ),
    ]
