# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_auto_20170910_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HTMLSourceTestData',
            new_name='RaceDayTestData',
        ),
        migrations.AddField(
            model_name='raceresulttestdata',
            name='race_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scrapper.RaceDayTestData'),
            preserve_default=False,
        ),
    ]
