# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0010_auto_20170910_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresulttestdata',
            name='race_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scrapper.RaceDayTestData'),
        ),
    ]
