# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0011_auto_20170910_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racedaytestdata',
            name='city',
        ),
        migrations.AddField(
            model_name='racedaytestdata',
            name='city_id',
            field=models.IntegerField(default=0),
        ),
    ]
