# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0012_auto_20170910_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racedaytestdata',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
